# Generated by Django 3.2.25 on 2024-10-04 14:12

from django.db import migrations, models
import news.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_article_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], max_length=10)),
                ('ordering', models.IntegerField(default=0)),
                ('link', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to=news.helpers.get_file_path),
        ),
    ]
